Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -13,21 +13,27 @@ jobs:
         uses: docker/setup-buildx-action@v3
       - name: Build Docker image
         run: docker build -t my-app:ci-test .
-      - name: Ensure curl and bash
+      - name: Set IMAGE_TAG
+        run: echo "IMAGE_TAG=rohit-ecr/my-app:${{ github.sha }}" >> $GITHUB_ENV
+      - name: Install curl/bash if needed
         run: |
-          if command -v curl >/dev/null 2>&1 && command -v bash >/dev/null 2>&1; then echo "curl/bash present"; else sudo apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq bash curl ca-certificates; fi
+          if command -v curl >/dev/null 2>&1 && command -v bash >/dev/null 2>&1; then
+            echo "curl/bash present"
+          else
+            sudo apt-get update -qq && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -qq bash curl ca-certificates
+          fi
       - name: Install FacetsCTL
         run: |
           curl -sSL https://facets-cloud.github.io/facets-schemas/scripts/fctl_install.sh | bash && source ~/.bashrc
-          if ! command -v fctl &> /dev/null; then echo "fctl not found on PATH"; fi
+          if ! command -v fctl &> /dev/null; then
+            echo "fctl not found on PATH"
+          fi
       - name: Export TOKEN
         run: echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
-      - name: Set IMAGE_TAG
-        run: echo "IMAGE_TAG=azure-cr/my-app:$GITHUB_SHA" >> $GITHUB_ENV
-      - name: Set Docker Image URL and Git Ref
+      - name: Export DOCKER_IMAGE_URL and GIT_REF
         run: |
-          echo "DOCKER_IMAGE_URL=$IMAGE_TAG" >> $GITHUB_ENV
-          echo "GIT_REF=$GITHUB_SHA" >> $GITHUB_ENV
+          echo "DOCKER_IMAGE_URL=${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
+          echo "GIT_REF=${{ github.sha }}" >> $GITHUB_ENV
       - name: Register Docker image with FacetsCTL
         run: |
           curl -s https://facets-cloud.github.io/facets-schemas/scripts/fctl_register.sh | bash -s -- \
@@ -35,5 +41,5 @@ jobs:
             -c "https://facetsdemo.console.facets.cloud" \
             -p "pet-clinic-satyendra" \
             -s "testing-ai" \
-            -a "azure-cr" \
+            -a "rohit-ecr" \
             -i "true"
